DROP TABLE IF EXISTS CASTS CASCADE;
DROP TABLE IF EXISTS MOVIE_DIRECTORS CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS ACTOR CASCADE;
DROP TABLE IF EXISTS MOVIE CASCADE;
DROP TABLE IF EXISTS DIRECTORS CASCADE;

CREATE TABLE ACTOR (
  id INTEGER,
  fname TEXT,
  lname TEXT,
  gender TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE MOVIE (
  id INTEGER,
  name TEXT,
  year INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE DIRECTORS (
  id INTEGER,
  fname TEXT,
  lname TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE CASTS (
  pid INTEGER,
  mid INTEGER,
  role TEXT,
  FOREIGN KEY (pid) REFERENCES ACTOR(id),
  FOREIGN KEY (mid) REFERENCES MOVIE(id)
);

CREATE TABLE MOVIE_DIRECTORS (
  did INTEGER,
  mid INTEGER,
  FOREIGN KEY (did) REFERENCES DIRECTORS(id),
  FOREIGN KEY (mid) REFERENCES MOVIE(id)
);

CREATE TABLE GENRE (
  mid INTEGER,
  genre TEXT
);

\COPY ACTOR FROM 'actor-ascii.txt' WITH DELIMITER '|' NULL AS '';
\COPY MOVIE FROM 'movie-ascii.txt' WITH DELIMITER '|' NULL AS '';
\COPY DIRECTORS FROM 'directors-ascii.txt' WITH DELIMITER '|' NULL AS '';
\COPY CASTS FROM 'casts-ascii.txt' WITH DELIMITER '|' NULL AS '';
\COPY MOVIE_DIRECTORS FROM 'movie_directors-ascii.txt' WITH DELIMITER '|' NULL AS '';
\COPY GENRE FROM 'genre-ascii.txt' WITH DELIMITER '|' NULL AS '';